// Generates shared/deployments/base-sepolia.json and shared/abi/*.ts from the Foundry
// build output and broadcast log. Run from anywhere: `npm run sync` at the repo root.
//
// Reads contracts/.env for the three demo addresses ONLY. Private keys are never read.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getAddress, isAddress } from "viem";

const sharedDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const contractsDir = join(sharedDir, "..", "contracts");

const CHAIN_ID = 84532;
const RPC_URL = "https://sepolia.base.org";
const EXPLORER_URL = "https://sepolia.basescan.org";

const readJson = (path) => JSON.parse(readFileSync(path, "utf8"));

function readEnvAddresses(path, keys) {
  const wanted = new Set(keys);
  const found = {};
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (!m || !wanted.has(m[1])) continue;
    const value = m[2].replace(/^["']|["']$/g, "");
    if (!isAddress(value)) throw new Error(`${m[1]} in contracts/.env is not an address`);
    found[m[1]] = getAddress(value);
  }
  for (const key of keys) if (!found[key]) throw new Error(`${key} missing from contracts/.env`);
  return found;
}

// --- Deployment ---------------------------------------------------------------

const run = readJson(join(contractsDir, "broadcast", "Deploy.s.sol", String(CHAIN_ID), "run-latest.json"));

function deployed(name) {
  const tx = run.transactions.find((t) => t.transactionType === "CREATE" && t.contractName === name);
  if (!tx) throw new Error(`No CREATE for ${name} in run-latest.json`);
  return getAddress(tx.contractAddress);
}

const deployBlock = Math.min(...run.receipts.map((r) => Number(BigInt(r.blockNumber))));
const env = readEnvAddresses(join(contractsDir, ".env"), ["AGENT_ADDRESS", "LEGIT_API_ADDRESS", "ATTACKER_ADDRESS"]);

const deployment = {
  network: "base-sepolia",
  chainId: CHAIN_ID,
  rpcUrl: RPC_URL,
  explorerUrl: EXPLORER_URL,
  deployBlock,
  usdcDecimals: 6,
  addresses: {
    vault: deployed("LeashVault"),
    usdc: deployed("MockUSDC"),
    oracle: deployed("MockReputationOracle"),
    agent: env.AGENT_ADDRESS,
    legitApi: env.LEGIT_API_ADDRESS,
    attacker: env.ATTACKER_ADDRESS,
  },
};

mkdirSync(join(sharedDir, "deployments"), { recursive: true });
writeFileSync(join(sharedDir, "deployments", "base-sepolia.json"), JSON.stringify(deployment, null, 2) + "\n");
console.log("wrote deployments/base-sepolia.json");

// --- ABIs ---------------------------------------------------------------------

const abis = [
  ["LeashVault", "leashVaultAbi"],
  ["MockUSDC", "mockUsdcAbi"],
  ["MockReputationOracle", "mockReputationOracleAbi"],
];

mkdirSync(join(sharedDir, "abi"), { recursive: true });
for (const [contract, exportName] of abis) {
  const { abi } = readJson(join(contractsDir, "out", `${contract}.sol`, `${contract}.json`));
  const source =
    `// Generated by shared/scripts/sync.mjs from contracts/out. Do not edit.\n\n` +
    `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(sharedDir, "abi", `${contract}.ts`), source);
  console.log(`wrote abi/${contract}.ts`);
}
